# Generated by Django 3.0.4 on 2020-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
