# Generated by Django 3.0.4 on 2020-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friend_acc_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
