# Generated by Django 3.0.4 on 2020-11-08 10:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='moderators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wall', models.IntegerField()),
                ('user', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='wall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('owner', models.CharField(default='', max_length=100)),
                ('visibility', models.IntegerField(choices=[(1, 'Public'), (2, 'Private')], default=1)),
                ('design', models.IntegerField(choices=[(1, 'Grid'), (2, 'Carousel')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Twitter', 'Twitter'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram')], max_length=15)),
                ('tag', models.CharField(max_length=100)),
                ('wall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.wall')),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date_posted', models.DateField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=200)),
                ('visibility', models.IntegerField(default=1)),
                ('author', models.CharField(default='', max_length=20)),
                ('platform', models.CharField(default='', max_length=20)),
                ('posted_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.wall')),
            ],
        ),
    ]
