# Generated by Django 3.0.4 on 2020-11-09 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderators',
            name='wall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall.wall'),
        ),
    ]
