# Generated by Django 3.0.4 on 2020-11-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0002_auto_20201109_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=300),
        ),
    ]
