# Generated by Django 3.0.4 on 2020-11-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20201111_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='last_id',
            field=models.IntegerField(default=0),
        ),
    ]
