# Generated by Django 3.0.4 on 2020-11-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0004_sources_last_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderators',
            name='status',
            field=models.BigIntegerField(default=0),
        ),
    ]
