# Generated by Django 3.0.4 on 2020-11-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0005_auto_20201114_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderators',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sources',
            name='last_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
