# Generated by Django 3.0.4 on 2020-11-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_wall_wall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wall',
            old_name='wall',
            new_name='logo',
        ),
    ]
